name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📂 Fix Google Services Path
        # Este comando garante que o arquivo esteja presente onde o Prebuild procura
        run: |
          ls -la google-services.json
          mkdir -p android/app
          cp google-services.json android/app/google-services.json || true

      - name: 📦 Install PNPM
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: 📦 Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🚀 Build APK
        # O uso do --clear-cache é obrigatório para aplicar as mudanças de caminho
        run: npx eas-cli build --platform android --profile production --local --non-interactive --clear-cache
