name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install PNPM
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: 📦 Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🚀 Build APK
        # Agora que o ID está no app.config.ts, rodamos direto o build
        run: npx eas-cli build --platform android --profile production --local --non-interactive
